name: Deploy Crawler to HF
on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Crawler Folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Cấu hình danh tính Git (Sửa lại đúng tên và email của bạn)
          git config --global user.email "phongphml@gmail.com"
          git config --global user.name "phongphml"
          
          # 2. Tách thư mục 'crawler' ra một nhánh tạm thời
          git subtree split --prefix crawler -b deploy-branch
          
          # 3. Ép buộc đẩy nhánh này lên Hugging Face (Sửa lại URL cho đúng user Phonghp)
          git push -f https://Phonghp:$HF_TOKEN@huggingface.co/spaces/Phonghp/crawler_web_truyen deploy-branch:main
