name: Deploy Crawler to HF
on:
  push:
    branches: [main] 
    paths:
      - 'crawler/**' # Chỉ chạy khi có thay đổi trong thư mục crawler

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Crawler Folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Đi vào thư mục crawler
          cd crawler
          
          # 2. Khởi tạo Git mới tại đây để xóa sạch lịch sử file > 10MB
          git init
          git config user.email "phongphml@gmail.com"
          git config user.name "phongphml"
          
          # 3. Thêm toàn bộ file hiện tại (đã chia nhỏ < 10MB)
          git add .
          git commit -m "Deploy clean version without large files"
          
          # 4. Ép buộc đẩy lên Hugging Face (Dùng -f)
          # Lưu ý: nhánh mặc định của 'git init' thường là 'master', nên ta đẩy master:main
          git push -f https://Phonghp:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/Phonghp/crawler_web_truyen master:main
