name: Deploy Crawler to HF
on:
  push:
    branches: [main] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Crawler Folder to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Cấu hình danh tính Git tạm thời cho máy chủ GitHub
          git config --global user.email "phongph@example.com"
          git config --global user.name "Phonghp"
          
          # Lệnh tách thư mục 'crawler' và đẩy lên Space
          git subtree push --prefix crawler https://Phonghp:$HF_TOKEN@huggingface.co/spaces/Phonghp/crawler_web_truyen main
